name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 4.2.0
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.18.0
  flutter_quill: #^10.1.2
    git: https://github.com/Arrunth/flutter-quill.git
  markdown: 
    git: https://github.com/Arrunth/markdown.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.10.0
  very_good_analysis: ^5.1.0
